package com.dj.eccom_backend.model;

public enum OrderStatus {
   PENDING_PAYMENT,
   PAYMENT_FAILED,
   PAID,
   CONFIRMED,
   PACKED,
   SHIPPED,
   IN_TRANSIT,
   DELIVERY_FAILED,
   DELIVERED,
   CANCELLED,
   RETURN_REQUESTED,
   RETURN_REJECTED,
   RETURNED,
   REFUNDED
}
